local_backend: false
backend:
  repo: sylasthekingslayer/wiki
  branch: main
  base_url: https://direnis.net
  name: github
  auth_endpoint: api/auth
media_folder: docs/public/images
public_folder: /images
collections:
  - name: eylem_bilgileri
    label: Eylem Bilgileri
    folder: docs
    create: true
    slug: "{{slug}}"
    fields:
      - label: Başlık
        name: title
        widget: string
      - label: İçerik
        name: body
        widget: markdown
  - name: hukuki_kaynaklar
    label: Hukuki Kaynaklar
    folder: docs
    create: true
    slug: "{{slug}}"
    fields:
      - label: Başlık
        name: title
        widget: string
      - label: İçerik
        name: body
        widget: markdown
  - name: diger
    label: Diğer
    folder: docs
    create: true
    slug: "{{slug}}"
    fields:
      - label: Başlık
        name: title
        widget: string
      - label: İçerik
        name: body
        widget: markdown
  - name: gundem
    label: Gündem
    folder: docs
    create: true
    slug: "{{slug}}"
    fields:
      - label: Başlık
        name: title
        widget: string
      - label: İçerik
        name: body
        widget: markdown
  - name: anasayfa
    label: Ana Sayfa
    folder: docs
    create: false
    slug: "{{slug}}"
    fields:
      - label: Başlık
        name: title
        widget: string
      - label: İçerik
        name: body
        widget: markdown
  - name: iletisim_bilgileri
    label: İletişim Bilgileri
    folder: docs
    create: true
    slug: "{{slug}}"
    fields:
      - label: Başlık
        name: title
        widget: string
      - label: İçerik
        name: body
        widget: markdown
