backend:
  name: github
  repo: sylasthekingslayer/wiki

media_folder: "docs/public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Sayfalar"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter" 
    fields:
      - { label: "Başlık", name: "title", widget: "string" } 
      - { label: "İçerik", name: "body", widget: "markdown" }
